### PR TITLE
adapt regex for new package names (master)

### PR DESCRIPTION
**Pull request by d-w-moore**
this belongs atop the pull request  #84  merged earlier today.

Cherry picked from the 4-2-stable version of that merged branch b/c now  Indexing Plugin tests are running in Jenkins

### CODE REVIEW

**Comment by trel** [comment]
very good, please # when confirmed/happy

**Comment by d-w-moore** [comment]
ok, testing in master to be sure

**Comment by d-w-moore** [comment]
Currently in iRODS 4.3.0 - land, Jenkins' build-irods-on-base will not build the Centos 7 irods-server.rpm package (no error logged, just -- that package is missing), so ... can't test the plugin on C7
Under ubuntu 18, we get all the way to run_plugin_tests and something can't load a shared object
```
Error encountered running setup_irods:
Traceback (most recent call last):
  File "/var/lib/irods/scripts/setup_irods.py", line 447, in main
    test_mode=options.test_mode)
  File "/var/lib/irods/scripts/setup_irods.py", line 68, in setup_server
    check_hostname()
  File "/var/lib/irods/scripts/setup_irods.py", line 168, in check_hostname
    if not irods.lib.hostname_resolves_to_local_address(hostname):
  File "/var/lib/irods/scripts/irods/lib.py", line 390, in hostname_resolves_to_local_address
    raise IrodsError('Error encountered in hostname_resolves_to_local_address for hostname [{0}]:\n{1}'.format(hostname, err))
IrodsError: Error encountered in hostname_resolves_to_local_address for hostname [icat.example.org]:
/usr/sbin/hostname_resolves_to_local_address: error while loading shared libraries: libc++abi.so.1: cannot open shared object file: No such file or directory
```

**Comment by d-w-moore** [comment]
This was merged separately

**Pull request closed without merging**
