### PR TITLE
[_122] prefer elasticlient version of libcpr

### PR DESCRIPTION
**Pull request by d-w-moore**

### CODE REVIEW

**Review by korydraughn — COMMENTED** [review]
Looks good.

Once all the tests pass for each OS, add the pound and merge it.

**Review by alanking — APPROVED** [review]
Yep. Please also link irods/irods#6437 in the commit message for posterity

**Comment by d-w-moore** [comment]
@alanking  is irods/irods#6437  related to the changes in this pull request?

**Comment by alanking** [comment]
In my view, yes. Can't check the box without this change because newer elasticlient is required on the new platforms

**Comment by d-w-moore** [comment]
So I'll add 6437 and # it as well, but will wait for @alanking 's changes to be pushed to this branch .  (changes with regard to proper detection of the almalinux platform and changing the plugin number to a more proper 4.3.0.0 instead of 4.3.0.1

**Comment by alanking** [comment]
I have confirmed almalinux:8 installs and passes with some changes on a branch of mine which @d-w-moore will cherry-pick shortly.

**Comment by d-w-moore** [comment]
squashed / #'d

**Pull request merged**
