### PR TITLE
add plugin and revision numbering

### PR DESCRIPTION
**Pull request by d-w-moore**

### CODE REVIEW

**Comment by trel** [comment]
is this working as desired?   please clean up the commit message if so, remove the 'conflicts' note.

**Comment by d-w-moore** [comment]
It is building as desired. The plugin dynamic .so's haven't changed only package versioning, so I would not expect the functioning to have broken ... but can check

**Comment by d-w-moore** [comment]
tested and working ; conflict message removed from  commit messages as well as comments

**Comment by d-w-moore** [comment]
ready for merge

**Pull request merged**
