### PR TITLE
Update dependencies in build hook (main)

### PR DESCRIPTION
**Pull request by korydraughn**

### CODE REVIEW

**Comment by trel** [comment]
yes

**Comment by korydraughn** [comment]
The following are referenced as dependencies in the build hook.
- irods-externals-cpr1.3.0-1
- irods-externals-elasticlientd68e30e3-0

We need to figure out what to do about #128.

**Comment by korydraughn** [comment]
See comment at https://github.com/irods/irods_capability_indexing/issues/128#issuecomment-1757880333 for current plan.

**Comment by alanking** [comment]
Do we need this anymore since #128 has been resolved?

**Comment by korydraughn** [comment]
This isn't needed anymore.

Why isn't github reporting a conflict or that this is a no-op? Am I blind or something?

**Comment by alanking** [comment]
Well, it is only a one-line change. Maybe it can rebase cleanly?

**Comment by korydraughn** [comment]
Well in any case, this PR isn't needed.

I'm going to close it unless you have opinions.

**Comment by alanking** [comment]
Yep, agreed. Close it

**Pull request closed without merging**
