### PR TITLE
[irods/irods#7265] Minor reorganization + CMake TLC

### PR DESCRIPTION
**Pull request by SwooshyCueb**
In service of irods/irods#7265

This does not break compatibility with 4.3.1.

I didn't notice that there was still an open PR (#141) until just now, so I'd prefer to wait until that is merged and then rebase.

### CODE REVIEW

**Comment by SwooshyCueb** [comment]
Done

**Comment by SwooshyCueb** [comment]
Once this PR is merged, please create a 4-3-stable branch

**Review by alanking — APPROVED** [review]
Feel free to ignore the suggested name change. I think everything looks fine as-is.

**Review by korydraughn — APPROVED** [review]
Looks good.

Pound it.

**Comment by SwooshyCueb** [comment]
\#'d

**Comment by alanking** [comment]
4-3-stable branch created based on https://github.com/irods/irods_capability_indexing/commit/8ac1fa1b4948a6ce5008d7bfcdd2e8c42d4f5b17

**Pull request merged**
