### PR TITLE
 [#91] implement flexible (integer|string) config vars (main)

### PR DESCRIPTION
**Pull request by d-w-moore**

### CODE REVIEW

**Comment by d-w-moore** [comment]
OK the test for #91 is working in 4.3.0 , since I tweaked `irods_log_level` to 7 in the service account irods_environment.json.

Per @korydraughn 's [recommendation here.](https://github.com/irods/irods_capability_indexing/pull/111#discussion_r864987628)

**Review by alanking — APPROVED** [review]
Need eyes from @korydraughn and @trel. Thanks!

**Review by korydraughn — APPROVED** [review]
Ship it!

**Comment by alanking** [comment]
And # here as well

**Comment by d-w-moore** [comment]
#'d here for merge into `main`

**Pull request merged**
